added GUI for the withdraw villager
Coolment-Content-Creation/SMP pull request #67
Opened 2024-01-05 06:29 UTC by paulpugh000

Builds off of #61 

Added the ability to use a GUI when interacting with 

## Tested Functionality
- Taking diamonds out of the UI takes money out of your balance (when the GUI is closed)
- Putting diamonds back into the UI adds money to your balance (to prevent weird unintuitive interactions, and only adds when the GUI is closed).

#### Additional functionality:
 - Action bar now shows your new balance when your balance updates
 - Fixed bug in #61 occurring when shutting off server and putting money into the bank

2024-01-05 21:46 UTC, paulpugh000 commented
Due to the way that the withdraw villager works, with the ability to also move stuff back into him, the name scheme seems like it could be made better. Currently there is a `deposit diamonds` villager and a `withdraw diamonds` villager, but I think it could be switched to something like `deposit box` and `bank teller`. With the ability for players to withdraw AND deposit items into the `bank teller` all the way up until ~Đ20k, it seems like the current `deposit` teller isn't needed until you have a large amount of wealth, which most players wont ever reach.

2024-01-05 22:24 UTC, NRProjects commented on src/main/java/plugins/nate/smp/SMP.java
Probably should be moved to TellerUtils

2024-01-05 22:24 UTC, NRProjects commented on src/main/java/plugins/nate/smp/SMP.java
> +        }
this for loop should probably just be a method in TellerUtils for cleanliness.

2024-01-05 22:39 UTC, NRProjects commented on src/main/java/plugins/nate/smp/listeners/TellerTradeListener.java
> +            VaultUtils.withdraw(player, diff);
This MUST use the same system as deposits as the withdraw() and deposit() methods return a boolean value.

If there's an exception or it returns false it could lead to possible item/money duplication glitches.


This is the pattern I used when doing deposits:
```java
boolean success = VaultUtils.deposit(player, totalValue);
        if (success) {
            sendMessage(player, PREFIX + "&aSuccessfully deposited " + (int) totalValue + CURRENCY_SYMBOL);
            displayBalance(player);
            inventory.clear();
        } else {
            sendMessage(player, PREFIX + "&cTransaction failed!");
            returnItemsToPlayer(inventory, player);
        }
```

2024-01-05 22:41 UTC, NRProjects commented on src/main/java/plugins/nate/smp/guis/TellerWithdrawGUI.java
> +        this.inventory = Bukkit.createInventory(this, 36, "Withdraw Diamonds");
Expand chest size to 54

2024-01-05 22:43 UTC, NRProjects requested changes
Works as intended. One glaring issue I noticed was the failure to handle failed transactions. Other than that it seems good.

2024-01-06 00:36 UTC, paulpugh000 commented on src/main/java/plugins/nate/smp/guis/TellerWithdrawGUI.java
> +        this.inventory = Bukkit.createInventory(this, 36, "Withdraw Diamonds");
The inventory size is good at 36, since a player can only hold 36 (37 with their off-hand included) items at a time in their inventory at once.

2024-01-06 00:56 UTC, paulpugh000 commented on src/main/java/plugins/nate/smp/listeners/TellerTradeListener.java
> +            VaultUtils.withdraw(player, diff);
A large rewrite will have to be done to solve a bug that can occur here. The balance only gets checked when the inventory is opened, and if the balance changes after opening the UI there can be a way of getting more currency out of the bank than what you actually own.

2024-01-15 10:56 UTC, paulpugh000 commented
In the most recent commit, I've added a couple of things.
- Validation of withdraws as outlined in https://github.com/Coolment-Content-Creation/SMP/pull/67#discussion_r1443496579
- Prevention of an exploit, where a player can "silently" close an inventory. (Closing an inventory client-side, without sending a packet to the server). 

Currency transactions get calculated when they close the withdraw teller's GUI, and the exploits are fixed by forcibly closing the inventories on the server side when a client tries opening another inventory, as well on death. The server already does this, but the timings are quite a bit off, so it is easier to simply close them again at the correct time.

A message gets broadcast to users with the `smp.tellerreport` permission node whenever someone opens an inventory, when they already have an inventory open.

**I did the following tests, using the [UI Utils Mod](https://github.com/Coderx-Gamer/ui-utils)**
1) Test the "silent" withdraw 
a)  Open the withdraw teller, and take out any amount of diamonds.
b) Close the withdraw teller "silently". Then do any of the 4:
    - Taking enough damage to die. This closes player open GUI instance and doing the calculations for the transaction, before it drops players items.
    - Reopen the withdraw teller. This also closes the old GUI that the server thinks is open.
    - Exit the game. This closes the GUI.
    - Drop the items. The items are unable to be dropped.
2) Attempting to drop items while in the withdraw GUI, which is now unable to occur.
3) Take money out insufficient funds
a) Open the withdraw teller, and take out any amount of diamonds.
b) Have money taken out of your account, resulting in your balance to be lower than the amount of diamonds you have taken out of the teller. When you close the teller, it will return the diamonds you have taken.

2024-01-20 21:46 UTC, NRProjects approved these changes

2024-01-20 21:47 UTC, merged