Added /live command
Coolment-Content-Creation/SMP pull request #77
Opened 2024-01-13 20:09 UTC by NRProjects

/live allows players with the `smp.live` permission to go /live.

This will set their group to `live` and from there we can decide what is done from there.

2024-01-13 23:49 UTC, Teelair requested changes
Mostly looks good, haven't personally tested it because I saw some minor issues.

2024-01-13 23:49 UTC, Teelair commented on src/main/java/plugins/nate/smp/commands/LiveCommand.java
> +            sendMessage(sender,  PREFIX + " &a" + player.getName() + " &7is no longer live!");
The tense on this is weird, because it's not a broadcast. I would change it to:

```suggestion
            sendMessage(sender, PREFIX + "&7You are no longer marked as live!");
```

2024-01-13 23:49 UTC, Teelair commented on src/main/java/plugins/nate/smp/commands/LiveCommand.java
> +            sendMessage(sender, PREFIX + " &a" + player.getName() + " is currently live!");
The tense on this is weird, because it's not a broadcast. I would change it to:

```suggestion
            sendMessage(sender, PREFIX + "&7You are now marked as live!");
```

2024-01-13 23:49 UTC, Teelair commented on src/main/java/plugins/nate/smp/utils/Permission.java
> +public class Permission {
I think this should be called `PermissionConstants` or something. I don't really like this pattern in general, but if this is the way we're going, that's fine. I would also raise a subsequent PR to standardize this.

2024-01-13 23:49 UTC, Teelair commented on src/main/java/plugins/nate/smp/commands/LiveCommand.java
> +                sendMessage(sender, PREFIX + "Only players can toggle their live status");
Should be red for an error.
```suggestion
                sendMessage(sender, PREFIX + "&cOnly players can toggle their live status");
```

2024-01-14 00:00 UTC, NRProjects commented on src/main/java/plugins/nate/smp/utils/Permission.java
> +public class Permission {
Changed!

2024-02-10 23:38 UTC, Teelair requested changes
The code looks good, but the functionality does not. When I mark myself no longer live, I'm not actually removed from the group.
![image](https://github.com/Coolment-Content-Creation/SMP/assets/22324401/9bd8e928-ff38-45fd-872c-90437022e884)

2024-02-19 10:10 UTC, merged