Added immediate liquidation of playerheads if interacted with
Coolment-Content-Creation/SMP pull request #80
Opened 2024-01-19 01:35 UTC by NRProjects

It makes it so that player heads will no longer be spawned on the server. This is a reoccurring issue, and this aims to prevent that at all costs.

Testing goals include trying to drop and place playerheads. You should not be able to interact with them at all. All interactions should be immediately deleted without notice. I've tested it and I cannot see how to break it

2024-01-22 15:57 UTC, paulpugh000 reviewed
There seems to be an excessive amount of checks, such as checking the whole inventory and any PlayerInteractEvent. I haven't tested it yet, but it looks good.

There should perhaps be a permission node to bypass some of these things, to where Coolment can still interact with heads, but players can't use them.

2024-01-22 15:59 UTC, Teelair commented
Let's hold on merging this for a bit. I'm interested in writing a script to check all the .mca files for illegal items, and this would become wasted work on a bunch of events if that pans out.

2024-01-22 21:00 UTC, NRProjects commented
It seems my PR was unclear. I have amended it and I am re-requesting reviews.

2024-02-10 23:53 UTC, Teelair requested changes
Generally looks okay enough, but you need to block off InventoryCreativeEvent too.

`This event is called when a player in creative mode puts down or picks up an item in their inventory / hotbar and when they drop items from their Inventory while in creative mode.`

https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/inventory/InventoryCreativeEvent.html

2024-02-10 23:53 UTC, Teelair commented on src/main/java/plugins/nate/smp/listeners/PlayerHeadListener.java
> +        }
The only subinterface of "HumanEntity" is "Player" and that's what event.getWhoClicked is an instanceof. (Weird, I know.) I feel like you're better off moving this check to the top of the method and just always having player in scope, but this is fine.

2024-02-10 23:53 UTC, Teelair commented on src/main/java/plugins/nate/smp/listeners/PlayerHeadListener.java
> +        }
This just stops someone from picking it up, doesn't stop it from existing

2024-02-10 23:53 UTC, Teelair commented on src/main/java/plugins/nate/smp/listeners/PlayerHeadListener.java
> +    public void onInventoryOpen(InventoryOpenEvent event) {
FYI, this won't be fired a player opening _their_ inventory. It gets fired for opening of a container or something.

2024-02-11 00:00 UTC, NRProjects commented on src/main/java/plugins/nate/smp/listeners/PlayerHeadListener.java
> +        }
The idea is that no one will be able to pick it up and it will despawn into oblivion

2024-02-11 00:01 UTC, NRProjects commented on src/main/java/plugins/nate/smp/listeners/PlayerHeadListener.java
> +    public void onInventoryOpen(InventoryOpenEvent event) {
That is the idea, any inventory opened should liquidate the item

2024-02-11 02:01 UTC, NRProjects commented
> Generally looks okay enough, but you need to block off InventoryCreativeEvent too.
> 
> `This event is called when a player in creative mode puts down or picks up an item in their inventory / hotbar and when they drop items from their Inventory while in creative mode.`
> 
> https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/inventory/InventoryCreativeEvent.html

Not sure if this is needed. It allows players in creative to grab heads but if they try to place them somewhere in the world it will just cancel the event. Also if they try to store it in a container it will just be vaporized next time its opened. Also if they try to drop it, players wont be able to pick it up.

2024-02-17 09:59 UTC, Teelair commented on src/main/java/plugins/nate/smp/listeners/PlayerHeadListener.java
> +        }
I suppose I'll let this fly. Though if someone were to spawn a bunch of heads in creative then drop them, this would literally just be an unstoppable lag pile for 5 minutes

2024-02-19 10:19 UTC, Teelair commented on src/main/java/plugins/nate/smp/listeners/PlayerHeadListener.java
> +        }
I take this back, it's only one line to clean them up proactively, so I went ahead and did that in 51f865d.

2024-02-19 10:21 UTC, Teelair approved these changes
LGTM

2024-02-19 10:21 UTC, Teelair commented on src/main/java/plugins/nate/smp/listeners/PlayerHeadListener.java
> +    }
```suggestion
        }
    }
```

2024-02-19 10:21 UTC, merged