PvP Toggle but built with a database
Coolment-Content-Creation/SMP pull request #93
Opened 2024-02-10 03:18 UTC by NRProjects

# MERGE #91 FIRST PLEASE
Closes #39 

This is meant to help players not be randomly murdered by other players constantly. It protects against negative potions, bows, crossbows, and direct attacks. Players with pvp disabled are still subject to attacks by player traps (lava pits, dispensers, etc.). PvP is disabled by default (this behavior is not included in this PR but in #91).

## Changes
Commands:
- `/pvp` and `/pvp help` display the help menu
- `/pvp toggle` toggles your pvp status
- `/pvp enable` enables your pvp status
- `/pvp disable` disables your pvp status

Admin Tools:
- Players with the `smp.bypasspvp permission bypass pvp status
- `/pvp set <username> <on|off>` sets a players pvp status

An action bar will be displayed when you have pvp enabled 100% of the time. If you get into combat, the action bar will change to display your current combat timer. If you log out during your combat timer you will be killed

## Things I've tested

- Melee attacks, potions, bows, crossbows do not work.
- Action bar works and displays accurate information
- You are not allowed to toggle your pvp status while in combat
- You will die on logout if you are in combat
- `/pvp set` works for all players

2024-02-10 22:35 UTC, Teelair commented
this PR title reads like a clickbait YT video, def LGTM

2024-02-19 04:20 UTC, Teelair requested changes
Looks mostly good, just a bunch of minor changes

2024-02-19 04:20 UTC, Teelair commented on src/main/java/plugins/nate/smp/listeners/PvPToggleListener.java
> +            PvPStatusUpdater.updatePlayerTitle(attacker);
```suggestion
```

The attacker shouldn't enter combat if their combat was unsuccessful

2024-02-19 04:20 UTC, Teelair commented on src/main/java/plugins/nate/smp/listeners/PvPToggleListener.java
> +            PvPManager.enterCombat(victim);
```suggestion
```

The victim shouldn't enter combat if they didn't attack?

2024-02-19 04:20 UTC, Teelair commented on src/main/java/plugins/nate/smp/listeners/PvPToggleListener.java
> +            PvPStatusUpdater.updatePlayerTitle(victim);
```suggestion
```

The victim shouldn't enter combat if they didn't attack?

2024-02-19 04:20 UTC, Teelair commented on src/main/java/plugins/nate/smp/listeners/PvPToggleListener.java
> +        }
Do the check for player thrower first, then calculate if the potion has a negative effect afterwards, instead of wasting work in the event this isn't a player.

```suggestion
        if (!(thrownPotion.getShooter() instanceof Player thrower)) {
            return;
        }
        
        boolean hasNegativeEffect = thrownPotion.getEffects().stream().anyMatch(effect -> PvPManager.negativeEffects.contains(effect.getType()));
        
        if (!hasNegativeEffect) {
            return;
        }
```

2024-02-19 04:20 UTC, Teelair commented on src/main/java/plugins/nate/smp/listeners/PvPToggleListener.java
> +                    }
```suggestion
                    if (!PlayerSettings.getPvPStatus(affectedPlayer.getUniqueId())) {
                        event.setIntensity(affectedPlayer, 0);
                        sendMessage(thrower, ChatUtils.PREFIX + "&c" + affectedPlayer.getName() + " has PvP disabled!");
                    }
                    
                    PvPManager.enterCombat(thrower);
```

Victims shouldn't enter combat

2024-02-19 04:20 UTC, Teelair commented on src/main/java/plugins/nate/smp/listeners/PvPToggleListener.java
> +    }
Have you tested this? Does this actually kill them and drop their stuff on logout?

(Do we also want a broadcast for combat loggers maybe?)

Edge case:
I start combat, I fight someone, I combat log, I log back in immediately, I log out again. Do I die again? (AKA, am I properly removed from the combat tracker?)

2024-02-19 04:20 UTC, Teelair commented on src/main/java/plugins/nate/smp/managers/PvPManager.java
> +    };
```suggestion
    private static final Map<UUID, Long> combatTimestamps = new ConcurrentHashMap<>();
```

2024-02-19 04:20 UTC, Teelair commented on src/main/java/plugins/nate/smp/managers/PvPManager.java
> +    private static final long COMBAT_COOLDOWN = 45 * 1000;
45 seconds is **awhile**. Maybe 15?

```suggestion
    private static final long COMBAT_COOLDOWN = 15 * 1000;
```

2024-02-19 04:20 UTC, Teelair commented on src/main/java/plugins/nate/smp/managers/PvPManager.java
> +
```suggestion
```

2024-02-19 04:20 UTC, Teelair commented on src/main/java/plugins/nate/smp/tables/PlayerSettings.java
> +     * A true return value indicates PvP is enabled
You could use Javadocs @returns here to be more idiomatic, won't block for this comment, just a nitpick

2024-02-19 04:20 UTC, Teelair commented on src/main/java/plugins/nate/smp/utils/PvPStatusUpdater.java
> +        ChatUtils.createActionBar(player, message);
Nitpick:

Technically, if you know you're going to concatenate a String, (and we are super guilty of this,) it's always better to use a StringBuilder, since that's what inline concatenation is doing under the hood anyway. So declaring message then doing += is spooling up another wasted object.

2024-02-19 04:26 UTC, NRProjects commented
TODO: Restore pvp to the default on player logoff

2024-02-19 04:27 UTC, NRProjects commented
TODO: Clear combatTimestamps map so on server restart everyone in PVP doesn't get murdered for combat logging

2024-02-19 04:31 UTC, NRProjects commented
TODO: Add bypass permission for staff members to not be added to the combatTimestamps map

2024-02-19 04:40 UTC, NRProjects commented on src/main/java/plugins/nate/smp/listeners/PvPToggleListener.java
> +    }
That does work. Added a broadcast messager

2024-02-19 04:45 UTC, NRProjects commented on src/main/java/plugins/nate/smp/utils/PvPStatusUpdater.java
> +        ChatUtils.createActionBar(player, message);
Good to know!

2024-02-19 05:13 UTC, NRProjects commented
TODO: Remove player from combat map on player death

2024-02-22 03:37 UTC, Teelair requested changes
Just a couple last minor things then this looks good to go.

2024-02-22 03:37 UTC, Teelair commented on src/main/java/plugins/nate/smp/commands/PvPCommand.java
> +                    .collect(Collectors.toList());
This will leak vanished players, but that's probably okay since this is behind a perm

2024-02-22 03:37 UTC, Teelair commented on src/main/java/plugins/nate/smp/commands/PvPCommand.java
> +            sendMessage(player, ChatUtils.PREFIX + "&cYou cannot change your pvp status in combat!");
```suggestion
            sendMessage(player, ChatUtils.PREFIX + "&cYou cannot change your pvp status while in combat!");
```

2024-02-22 03:37 UTC, Teelair commented on src/main/java/plugins/nate/smp/commands/PvPCommand.java
> +            sendMessage(player, ChatUtils.PREFIX + "&cYou cannot change your pvp status in combat!");
```suggestion
            sendMessage(player, ChatUtils.PREFIX + "&cYou cannot change your pvp status while in combat!");
```

2024-02-22 03:37 UTC, Teelair commented on src/main/java/plugins/nate/smp/commands/PvPCommand.java
> +        sendMessage(sender, "&8&m-----------------------------------------------------");
```suggestion
```

2024-02-22 03:37 UTC, Teelair commented on src/main/java/plugins/nate/smp/commands/DevCommand.java
> +import plugins.nate.smp.tables.PlayerSettings;
This (with all other changes in the file) should go away
```suggestion
```

2024-02-22 03:37 UTC, Teelair commented on src/main/java/plugins/nate/smp/commands/DevCommand.java
> +            }
```suggestion
```

This should go away

2024-02-22 03:37 UTC, Teelair commented on src/main/java/plugins/nate/smp/listeners/PvPToggleListener.java
> +                        SMPUtils.log(thrower.getName());
This is hanging logging it looks like?
```suggestion
```

2024-02-22 03:37 UTC, Teelair commented on src/main/java/plugins/nate/smp/listeners/PvPToggleListener.java
> +            Bukkit.broadcastMessage(ChatColor.translateAlternateColorCodes('&', ChatUtils.PREFIX + "&c" + event.getPlayer().getName() + " has combat logged and been killed as a result!"));
```suggestion
            Bukkit.broadcastMessage(ChatColor.translateAlternateColorCodes('&', ChatUtils.PREFIX + "&c" + event.getPlayer().getName() + " has combat logged and was killed as a result!"));
```

2024-02-22 03:37 UTC, Teelair commented on src/main/java/plugins/nate/smp/listeners/database/JoinListener.java
> +    }
This should probably consolidate into PvPToggleListener?

2024-02-22 03:37 UTC, Teelair commented on src/main/java/plugins/nate/smp/tables/PlayerSettings.java
> +     * @param pvpEnabled 0 is disabled, 1 is enabled
```suggestion
     * @param pvpEnabled false is disabled, true is enabled
```

2024-02-22 03:37 UTC, Teelair commented on src/main/java/plugins/nate/smp/tables/PlayerSettings.java
> +>>>>>>> Stashed changes
```suggestion
     * @return true if PvP is enabled, false if it is disabled
```

2024-02-22 03:37 UTC, Teelair commented on src/main/java/plugins/nate/smp/utils/PvPStatusUpdater.java
> +
```suggestion
```

2024-02-22 07:17 UTC, Teelair approved these changes
Looks good to me. Made some minor changes, but this will ship tonight.

2024-02-22 07:17 UTC, merged